title: Jekyll-GOVUK theme demo
description: A minimal GOV.UK styled Jekyll theme.

theme: null

sass:
  load_paths:
    - _sass

# Optional site-wide navigation
header_links:
  - name: Home
    url: /
  - name: About
    url: /about/

# Optional footer links
footer_links:
  - name: Accessibility
    url: /accessibility/
  - name: Privacy
    url: /privacy/
