title: Jekyll-GOVUK theme demo
description: A minimal GOV.UK styled Jekyll theme.
baseurl: "/jekyll-govuk"  # Important for GH Pages subpath

url: ""     # e.g. https://yourdomain.com

theme: null
theme_color: "#0b0c0c"
use_gds_fonts: false
custom_site_logo_width: true

# Optional site-wide navigation
header_links:
  - name: Home
    url: /
  - name: About
    url: /about/

# Optional footer links
footer_links:
  - name: Accessibility
    url: /accessibility/
  - name: Privacy
    url: /privacy/