title: Jekyll-GOVUK theme demo
description: A minimal GOV.UK styled Jekyll theme.
baseurl: "/jekyll-govuk"
url: "https://jonathanthomas83.github.io"

# Optional site-wide navigation
header_links:
  - name: Home
    url: /
  - name: About
    url: /about/

# Optional footer links
footer_links:
  - name: Accessibility
    url: /accessibility/
  - name: Privacy
    url: /privacy/
